/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Which adapter is plugged into each seam: the System status page reads this.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description The chat list, most recent activity first. A session with no messages yet isn't listed.
         *     Untitled sessions (from before titles existed) get their first message as the title.
         */
        get: operations["list_sessions_api_chat_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_chat_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Deletes the chat and its messages for good. Approval cards it produced stay on the
         *     Approvals page and in the audit log.
         */
        delete: operations["delete_session_api_chat_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_chat_sessions__session_id__messages_get"];
        put?: never;
        /** Post Message */
        post: operations["post_message_api_chat_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proposals */
        get: operations["list_proposals_api_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proposal */
        get: operations["get_proposal_api_proposals__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description Approve, edit-then-approve, or reject. The only way an agent write ever executes.
         */
        post: operations["decide_api_proposals__proposal_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tools
         * @description The agent's tools and their argument schemas (the approval card's Edit form uses these).
         */
        get: operations["list_tools_api_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Folders */
        get: operations["list_folders_api_folders_get"];
        put?: never;
        /** Create Folder */
        post: operations["create_folder_api_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders/{folder_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_folders__folder_id__items_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_folders__folder_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_api_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reminders */
        get: operations["list_reminders_api_reminders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reminders/{reminder_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Reminder */
        post: operations["cancel_reminder_api_reminders__reminder_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Today
         * @description The Today board and daily brief: today's reminders and events, free time left, newest
         *     unread mail, this week's tasks and what's waiting for approval.
         */
        get: operations["today_api_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/week": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Week */
        get: operations["week_api_week_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/week/schedule-task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schedule Task
         * @description Propose a calendar event for the task in the first free slot that fits (approval card).
         */
        post: operations["schedule_task_api_week_schedule_task_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inbox */
        get: operations["inbox_api_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbox/{message_id}/draft-reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draft Reply
         * @description A reply to the sender, written by the local model, as an approval card (nothing is sent
         *     until the owner approves it, and the card shows the whole text).
         */
        post: operations["draft_reply_api_inbox__message_id__draft_reply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        /**
         * Upload
         * @description Store a PDF, Word .docx or text/Markdown file and index its text for questions.
         */
        post: operations["upload_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Answer from the owner's documents only, citing passages as [n].
         */
        post: operations["ask_api_documents_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suggestions */
        get: operations["list_suggestions_api_memory_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/suggestions/{suggestion_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Suggestion */
        post: operations["decide_suggestion_api_memory_suggestions__suggestion_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Facts */
        get: operations["list_facts_api_memory_facts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/facts/{fact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Fact */
        delete: operations["delete_fact_api_memory_facts__fact_id__delete"];
        options?: never;
        head?: never;
        /**
         * Edit Fact
         * @description The owner corrects a remembered fact. A direct edit by the owner, so no approval card.
         */
        patch: operations["edit_fact_api_memory_facts__fact_id__patch"];
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Everything */
        get: operations["export_everything_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transcribe */
        post: operations["transcribe_api_voice_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/speak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Speak */
        post: operations["speak_api_voice_speak_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/vapid-public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vapid Public Key */
        get: operations["vapid_public_key_api_push_vapid_public_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe */
        post: operations["subscribe_api_push_subscriptions_post"];
        /** Unsubscribe */
        delete: operations["unsubscribe_api_push_subscriptions_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Test */
        post: operations["send_test_api_push_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ack
         * @description Called by the service worker when a push arrives: this is how latency gets measured.
         */
        post: operations["ack_api_push_ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deliveries */
        get: operations["deliveries_api_push_deliveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notification Settings */
        get: operations["get_notification_settings_api_settings_notifications_get"];
        /** Put Notification Settings */
        put: operations["put_notification_settings_api_settings_notifications_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Mfa */
        post: operations["verify_mfa_api_auth_mfa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll Mfa */
        post: operations["enroll_mfa_api_auth_mfa_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/enroll/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Mfa
         * @description Finish enrolment with the first code from the authenticator app. Until this succeeds,
         *     two-step verification is NOT on (a scanned QR code alone changes nothing).
         */
        post: operations["confirm_mfa_api_auth_mfa_enroll_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AckIn */
        AckIn: {
            /** Notification Id */
            notification_id: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
        };
        /**
         * Actor
         * @enum {string}
         */
        Actor: "user" | "agent" | "system";
        /** AdapterInfo */
        AdapterInfo: {
            /** Name */
            name: string;
            /** Fake */
            fake: boolean;
        };
        /** AnswerOut */
        AnswerOut: {
            /** Answer */
            answer: string;
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            /** Cited */
            cited: boolean;
        };
        /** AskIn */
        AskIn: {
            /** Question */
            question: string;
        };
        /** AuditEntry */
        AuditEntry: {
            /** Id */
            id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            actor: components["schemas"]["Actor"];
            /** Action */
            action: string;
            /** Target */
            target?: string | null;
            /**
             * Detail
             * @default {}
             */
            detail: {
                [key: string]: unknown;
            };
        };
        /** CalendarEvent */
        CalendarEvent: {
            /** Id */
            id?: string | null;
            /** Title */
            title: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Location */
            location?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            role: components["schemas"]["Role"];
            /** Text */
            text: string;
            /**
             * Source
             * @default text
             * @enum {string}
             */
            source: "text" | "voice";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Emails
             * @default []
             */
            emails: components["schemas"]["EmailSummary"][];
        };
        /** ChatSession */
        ChatSession: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Message At */
            last_message_at?: string | null;
        };
        /** CreateFolderIn */
        CreateFolderIn: {
            /** Name */
            name: string;
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["FieldDef"][];
        };
        /** CreateItemIn */
        CreateItemIn: {
            /** Title */
            title: string;
            /**
             * Fields
             * @default {}
             */
            fields: {
                [key: string]: unknown;
            };
        };
        /** CreateSessionIn */
        CreateSessionIn: {
            /** Title */
            title?: string | null;
        };
        /** CreateTaskIn */
        CreateTaskIn: {
            /** Title */
            title: string;
            /** @default week */
            horizon: components["schemas"]["Horizon"];
            /** Folder Id */
            folder_id?: string | null;
            /** Due At */
            due_at?: string | null;
        };
        /** DayPlan */
        DayPlan: {
            /** Date */
            date: string;
            /** Events */
            events: components["schemas"]["CalendarEvent"][];
            /** Free Slots */
            free_slots: components["schemas"]["TimeRange"][];
            /** Reminders */
            reminders: components["schemas"]["Reminder"][];
            /** Tasks Due */
            tasks_due: components["schemas"]["Task"][];
        };
        /** DecisionIn */
        DecisionIn: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject" | "edit";
            /** Args */
            args?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * Delivery
         * @description Delivery record used to measure the 'reminder reaches the phone within 60 s' target.
         */
        Delivery: {
            /** Notification Id */
            notification_id: string;
            kind: components["schemas"]["NotificationKind"];
            /** Due At */
            due_at?: string | null;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
            /** Received At */
            received_at?: string | null;
        };
        /** DeliveryResult */
        DeliveryResult: {
            /** Notification Id */
            notification_id: string;
            /** Delivered */
            delivered: number;
            /**
             * Deferred
             * @default false
             */
            deferred: boolean;
            /** Detail */
            detail?: string | null;
            /**
             * Failed
             * @default 0
             */
            failed: number;
        };
        /**
         * Document
         * @description An uploaded file. The bytes live in the file store under `storage_key`; its text, cut
         *     into passages with embeddings, in the document repository.
         */
        Document: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Content Type */
            content_type: string;
            /** Size */
            size: number;
            /** Pages */
            pages?: number | null;
            /**
             * Passages
             * @default 0
             */
            passages: number;
            /** Note */
            note?: string | null;
            /** Storage Key */
            storage_key: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EmailSummary */
        EmailSummary: {
            /** Id */
            id: string;
            /** Sender */
            sender: string;
            /** Subject */
            subject: string;
            /** Snippet */
            snippet: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /**
             * Unread
             * @default true
             */
            unread: boolean;
            /**
             * Labels
             * @default []
             */
            labels: string[];
        };
        /** ExportOut */
        ExportOut: {
            /**
             * Exported At
             * Format: date-time
             */
            exported_at: string;
            /** Folders */
            folders: components["schemas"]["Folder"][];
            /** Items */
            items: components["schemas"]["Item"][];
            /** Tasks */
            tasks: components["schemas"]["Task"][];
            /** Reminders */
            reminders: components["schemas"]["Reminder"][];
            /** Facts */
            facts: components["schemas"]["MemoryFact"][];
            /** Suggestions */
            suggestions: components["schemas"]["MemorySuggestion"][];
            /** Proposals */
            proposals: components["schemas"]["Proposal"][];
            /** Chat Sessions */
            chat_sessions: components["schemas"]["ChatSession"][];
            /** Chat Messages */
            chat_messages: components["schemas"]["ChatMessage"][];
            /** Audit */
            audit: components["schemas"]["AuditEntry"][];
        };
        /**
         * FactUpdateIn
         * @description PATCH /api/memory/facts/{id} (added Sep 30, additive): the owner corrects a fact.
         */
        FactUpdateIn: {
            /** Text */
            text: string;
        };
        /** FieldDef */
        FieldDef: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** @default text */
            type: components["schemas"]["FieldType"];
            /** Options */
            options?: string[] | null;
        };
        /**
         * FieldType
         * @enum {string}
         */
        FieldType: "text" | "number" | "date" | "select" | "rating" | "bool";
        /** Folder */
        Folder: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** @default custom */
            kind: components["schemas"]["FolderKind"];
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["FieldDef"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FolderKind
         * @enum {string}
         */
        FolderKind: "para" | "custom";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /** Adapters */
            adapters: {
                [key: string]: components["schemas"]["AdapterInfo"];
            };
        };
        /**
         * Horizon
         * @enum {string}
         */
        Horizon: "week" | "term" | "year" | "someday";
        /** InboxOut */
        InboxOut: {
            /** Items */
            items: components["schemas"]["TriagedEmail"][];
            /** Error */
            error?: string | null;
        };
        /** Item */
        Item: {
            /** Id */
            id: string;
            /** Folder Id */
            folder_id: string;
            /** Title */
            title: string;
            /**
             * Fields
             * @default {}
             */
            fields: {
                [key: string]: unknown;
            };
            /** Source */
            source?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginOut */
        LoginOut: {
            /** Mfa Required */
            mfa_required: boolean;
            /** Challenge Id */
            challenge_id?: string | null;
        };
        /** MemoryFact */
        MemoryFact: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Source */
            source: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MemorySuggestion
         * @description A fact the agent noticed. Stored as a MemoryFact only if the owner approves it.
         */
        MemorySuggestion: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Source */
            source: string;
            /** @default pending */
            status: components["schemas"]["SuggestionStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MfaConfirmIn
         * @description POST /api/auth/mfa/enroll/confirm (added Sep 30, additive): the first code from the app.
         */
        MfaConfirmIn: {
            /** Code */
            code: string;
        };
        /** MfaEnrollOut */
        MfaEnrollOut: {
            /** Otpauth Uri */
            otpauth_uri: string;
        };
        /** MfaIn */
        MfaIn: {
            /** Challenge Id */
            challenge_id: string;
            /** Code */
            code: string;
        };
        /**
         * NotificationKind
         * @enum {string}
         */
        NotificationKind: "reminder" | "brief" | "system" | "test";
        /** NotificationSettings */
        NotificationSettings: {
            quiet_hours?: components["schemas"]["QuietHours"] | null;
            /**
             * Timezone
             * @default America/Toronto
             */
            timezone: string;
            /**
             * Max Per Hour
             * @default 6
             */
            max_per_hour: number;
            /**
             * Private Previews
             * @default false
             */
            private_previews: boolean;
            /** Checkin At */
            checkin_at?: string | null;
        };
        /** PatchTaskIn */
        PatchTaskIn: {
            /** Title */
            title?: string | null;
            horizon?: components["schemas"]["Horizon"] | null;
            /** Done */
            done?: boolean | null;
            /** Due At */
            due_at?: string | null;
        };
        /** PostMessageIn */
        PostMessageIn: {
            /** Text */
            text: string;
            /**
             * Source
             * @default text
             * @enum {string}
             */
            source: "text" | "voice";
        };
        /**
         * Proposal
         * @description A write the agent wants to make. Nothing runs until the owner approves it.
         */
        Proposal: {
            /** Id */
            id: string;
            /** Session Id */
            session_id?: string | null;
            /** Tool */
            tool: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /** Preview */
            preview?: string | null;
            /** Warnings */
            warnings?: string[];
            /** @default write */
            risk: components["schemas"]["Risk"];
            /** @default pending */
            status: components["schemas"]["ProposalStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at?: string | null;
            /** Result */
            result?: string | null;
        };
        /**
         * ProposalStatus
         * @enum {string}
         */
        ProposalStatus: "pending" | "approved" | "rejected" | "executed" | "failed";
        /** PushKeys */
        PushKeys: {
            /** P256Dh */
            p256dh: string;
            /** Auth */
            auth: string;
        };
        /** QuietHours */
        QuietHours: {
            /**
             * Start
             * Format: time
             */
            start: string;
            /**
             * End
             * Format: time
             */
            end: string;
        };
        /** Reminder */
        Reminder: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Recurrence */
            recurrence?: string | null;
            /** @default scheduled */
            status: components["schemas"]["ReminderStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sent At */
            sent_at?: string | null;
        };
        /**
         * ReminderStatus
         * @enum {string}
         */
        ReminderStatus: "scheduled" | "sent" | "cancelled";
        /**
         * Risk
         * @enum {string}
         */
        Risk: "write" | "external";
        /**
         * Role
         * @enum {string}
         */
        Role: "user" | "assistant";
        /** ScheduleTaskIn */
        ScheduleTaskIn: {
            /** Task Id */
            task_id: string;
            /**
             * Minutes
             * @default 60
             */
            minutes: number;
        };
        /** SourceOut */
        SourceOut: {
            /** N */
            n: number;
            /** Document Id */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Page */
            page?: number | null;
            /** Excerpt */
            excerpt: string;
        };
        /** SpeakIn */
        SpeakIn: {
            /** Text */
            text: string;
            /** Voice */
            voice?: string | null;
        };
        /** SubscriptionIn */
        SubscriptionIn: {
            /** Endpoint */
            endpoint: string;
            keys: components["schemas"]["PushKeys"];
            /** User Agent */
            user_agent?: string | null;
        };
        /** SuggestionDecisionIn */
        SuggestionDecisionIn: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
        };
        /**
         * SuggestionStatus
         * @enum {string}
         */
        SuggestionStatus: "pending" | "approved" | "rejected";
        /** Task */
        Task: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** @default week */
            horizon: components["schemas"]["Horizon"];
            /** Folder Id */
            folder_id?: string | null;
            /** Due At */
            due_at?: string | null;
            /**
             * Done
             * @default false
             */
            done: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TimeRange */
        TimeRange: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** TodayOut */
        TodayOut: {
            /** Date */
            date: string;
            /** Timezone */
            timezone: string;
            /** Reminders */
            reminders: components["schemas"]["Reminder"][];
            /** Tasks */
            tasks: components["schemas"]["Task"][];
            /** Pending Proposals */
            pending_proposals: components["schemas"]["Proposal"][];
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["CalendarEvent"][];
            /**
             * Free Slots
             * @default []
             */
            free_slots: components["schemas"]["TimeRange"][];
            /**
             * Unread
             * @default []
             */
            unread: components["schemas"]["EmailSummary"][];
            /** Calendar Error */
            calendar_error?: string | null;
            /** Mail Error */
            mail_error?: string | null;
        };
        /** ToolInfo */
        ToolInfo: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Read Only */
            read_only: boolean;
            risk: components["schemas"]["Risk"];
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
        };
        /** Transcript */
        Transcript: {
            /** Text */
            text: string;
            /** Language */
            language?: string | null;
            /** Duration Ms */
            duration_ms: number;
            /** Stt Ms */
            stt_ms: number;
        };
        /** TriagedEmail */
        TriagedEmail: {
            email: components["schemas"]["EmailSummary"];
            /**
             * Category
             * @enum {string}
             */
            category: "reply" | "fyi" | "low";
            /** Reason */
            reason: string;
            /** Suspicious */
            suspicious: boolean;
            /**
             * Sorted By
             * @enum {string}
             */
            sorted_by: "rules" | "model";
        };
        /** UnsubscribeIn */
        UnsubscribeIn: {
            /** Endpoint */
            endpoint: string;
        };
        /** User */
        User: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /**
             * Mfa Enabled
             * @default false
             */
            mfa_enabled: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VapidKeyOut */
        VapidKeyOut: {
            /** Public Key */
            public_key: string | null;
        };
        /**
         * WeekOut
         * @description The next 7 days, starting today, plus this week's tasks that have no date yet.
         */
        WeekOut: {
            /** Timezone */
            timezone: string;
            /** Days */
            days: components["schemas"]["DayPlan"][];
            /** Unscheduled */
            unscheduled: components["schemas"]["Task"][];
            /** Calendar Error */
            calendar_error?: string | null;
        };
        /** ErrorEvent */
        ErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** MessageDelta */
        MessageDelta: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.delta";
            /** Text */
            text: string;
        };
        /** MessageDone */
        MessageDone: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.done";
            /** Message Id */
            message_id: string;
            /**
             * Ttft Ms
             * @default null
             */
            ttft_ms: number | null;
            /**
             * Tokens
             * @default null
             */
            tokens: number | null;
        };
        /** ProposalCreated */
        ProposalCreated: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "proposal.created";
            proposal: components["schemas"]["Proposal"];
        };
        /** ToolResult */
        ToolResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.result";
            /** Call Id */
            call_id: string;
            /** Ok */
            ok: boolean;
            /** Summary */
            summary: string;
            /**
             * Emails
             * @default []
             */
            emails: components["schemas"]["EmailSummary"][];
        };
        /** ToolStarted */
        ToolStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.started";
            /** Call Id */
            call_id: string;
            /** Tool */
            tool: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
        };
        ChatEvent: components["schemas"]["MessageDelta"] | components["schemas"]["ToolStarted"] | components["schemas"]["ToolResult"] | components["schemas"]["ProposalCreated"] | components["schemas"]["MessageDone"] | components["schemas"]["ErrorEvent"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_sessions_api_chat_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"][];
                };
            };
        };
    };
    create_session_api_chat_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_chat_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_chat_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_api_chat_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostMessageIn"];
            };
        };
        responses: {
            /** @description Server-sent events. Each frame is `event: <type>` + `data: <ChatEvent JSON>`; `: ping` comments are heartbeats. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ChatEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_proposals_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProposalStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_api_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_proposals__proposal_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_api_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInfo"][];
                };
            };
        };
    };
    list_folders_api_folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Folder"][];
                };
            };
        };
    };
    create_folder_api_folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Folder"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_folders__folder_id__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_folders__folder_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                horizon?: components["schemas"]["Horizon"] | null;
                done?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchTaskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reminders_api_reminders_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ReminderStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_reminder_api_reminders__reminder_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    today_api_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayOut"];
                };
            };
        };
    };
    week_api_week_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekOut"];
                };
            };
        };
    };
    schedule_task_api_week_schedule_task_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleTaskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inbox_api_inbox_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxOut"];
                };
            };
        };
    };
    draft_reply_api_inbox__message_id__draft_reply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
        };
    };
    upload_api_documents_post: {
        parameters: {
            query: {
                /** @description The file's name, e.g. syllabus.pdf */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_documents_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suggestions_api_memory_suggestions_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["SuggestionStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySuggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_suggestion_api_memory_suggestions__suggestion_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySuggestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facts_api_memory_facts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryFact"][];
                };
            };
        };
    };
    delete_fact_api_memory_facts__fact_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_fact_api_memory_facts__fact_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryFact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_everything_api_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
        };
    };
    transcribe_api_voice_transcribe_post: {
        parameters: {
            query?: {
                language?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "audio/webm": string;
                "audio/mp4": string;
                "audio/ogg": string;
                "audio/wav": string;
                "audio/mpeg": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transcript"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    speak_api_voice_speak_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vapid_public_key_api_push_vapid_public_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VapidKeyOut"];
                };
            };
        };
    };
    subscribe_api_push_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_api_push_subscriptions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnsubscribeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_test_api_push_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryResult"];
                };
            };
        };
    };
    ack_api_push_ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deliveries_api_push_deliveries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivery"][];
                };
            };
        };
    };
    get_notification_settings_api_settings_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
        };
    };
    put_notification_settings_api_settings_notifications_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description wrong username or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description locked */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_mfa_api_auth_mfa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_mfa_api_auth_mfa_enroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaEnrollOut"];
                };
            };
            /** @description the dev login can't enable two-step verification */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirm_mfa_api_auth_mfa_enroll_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the code doesn't match */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the dev login can't enable two-step verification */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
}
